CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.product (
    id serial PRIMARY KEY,
    brandId INTEGER NOT NULL,
    title VARCHAR(255)
);

INSERT INTO product(brandId,title) VALUES (9,'Tuna - Bluefin');
INSERT INTO product(brandId,title) VALUES (59,'Oil - Olive, Extra Virgin');
INSERT INTO product(brandId,title) VALUES (63,'Ecolab - Solid Fusion');
INSERT INTO product(brandId,title) VALUES (20,'Coffee Beans - Chocolate');
INSERT INTO product(brandId,title) VALUES (42,'Vodka - Lemon, Absolut');
INSERT INTO product(brandId,title) VALUES (23,'Flour - All Purpose');
INSERT INTO product(brandId,title) VALUES (60,'Wine - Zinfandel California 2002');
INSERT INTO product(brandId,title) VALUES (82,'Bread - Dark Rye');
INSERT INTO product(brandId,title) VALUES (21,'Soho Lychee Liqueur');
INSERT INTO product(brandId,title) VALUES (85,'Napkin - Beverage 1 Ply');
INSERT INTO product(brandId,title) VALUES (97,'Capon - Breast, Double, Wing On');
INSERT INTO product(brandId,title) VALUES (31,'Campari');
INSERT INTO product(brandId,title) VALUES (4,'Quail - Whole, Boneless');
INSERT INTO product(brandId,title) VALUES (78,'Muffin - Blueberry Individual');
INSERT INTO product(brandId,title) VALUES (92,'Icecream Cone - Areo Chocolate');
INSERT INTO product(brandId,title) VALUES (30,'Dill Weed - Dry');
INSERT INTO product(brandId,title) VALUES (37,'Cheese - Shred Cheddar / Mozza');
INSERT INTO product(brandId,title) VALUES (45,'Energy Drink - Redbull 355ml');
INSERT INTO product(brandId,title) VALUES (98,'Ginger - Ground');
INSERT INTO product(brandId,title) VALUES (98,'Pur Value');
INSERT INTO product(brandId,title) VALUES (49,'Lemon Grass');
INSERT INTO product(brandId,title) VALUES (27,'Irish Cream - Baileys');
INSERT INTO product(brandId,title) VALUES (26,'Sour Puss - Tangerine');
INSERT INTO product(brandId,title) VALUES (17,'Pie Shells 10');
INSERT INTO product(brandId,title) VALUES (7,'Chickhen - Chicken Phyllo');
INSERT INTO product(brandId,title) VALUES (39,'Food Colouring - Pink');
INSERT INTO product(brandId,title) VALUES (56,'Bag Stand');
INSERT INTO product(brandId,title) VALUES (46,'Island Oasis - Wildberry');
INSERT INTO product(brandId,title) VALUES (8,'Garlic - Primerba, Paste');
INSERT INTO product(brandId,title) VALUES (88,'Mangostein');
INSERT INTO product(brandId,title) VALUES (4,'Juice - Grape, White');
INSERT INTO product(brandId,title) VALUES (41,'Sprouts - Brussel');
INSERT INTO product(brandId,title) VALUES (74,'Tea Leaves - Oolong');
INSERT INTO product(brandId,title) VALUES (39,'Shiro Miso');
INSERT INTO product(brandId,title) VALUES (16,'Tart Shells - Sweet, 4');
INSERT INTO product(brandId,title) VALUES (86,'Appetizer - Chicken Satay');
INSERT INTO product(brandId,title) VALUES (1,'Plaintain');
INSERT INTO product(brandId,title) VALUES (94,'Cheese - Brick With Onion');
INSERT INTO product(brandId,title) VALUES (41,'Wine - Chianti Classica Docg');
INSERT INTO product(brandId,title) VALUES (54,'Cinnamon Buns Sticky');
INSERT INTO product(brandId,title) VALUES (37,'Ice Cream - Fudge Bars');
INSERT INTO product(brandId,title) VALUES (34,'Pineapple - Golden');
INSERT INTO product(brandId,title) VALUES (69,'Pasta - Canelloni, Single Serve');
INSERT INTO product(brandId,title) VALUES (91,'Table Cloth - 53x69 Colour');
INSERT INTO product(brandId,title) VALUES (12,'Dry Ice');
INSERT INTO product(brandId,title) VALUES (33,'Bandage - Fexible 1x3');
INSERT INTO product(brandId,title) VALUES (21,'Bacardi Breezer - Tropical');
INSERT INTO product(brandId,title) VALUES (80,'Nut - Pumpkin Seeds');
INSERT INTO product(brandId,title) VALUES (71,'Burger Veggie');
INSERT INTO product(brandId,title) VALUES (22,'Wine - Magnotta, White');
INSERT INTO product(brandId,title) VALUES (81,'Beer - Blue Light');
INSERT INTO product(brandId,title) VALUES (47,'Lamb - Ground');
INSERT INTO product(brandId,title) VALUES (61,'Table Cloth 91x91 Colour');
INSERT INTO product(brandId,title) VALUES (74,'Cucumber - English');
INSERT INTO product(brandId,title) VALUES (81,'Lettuce - Belgian Endive');
INSERT INTO product(brandId,title) VALUES (57,'Petit Baguette');
INSERT INTO product(brandId,title) VALUES (73,'Gooseberry');
INSERT INTO product(brandId,title) VALUES (42,'Spaghetti Squash');
INSERT INTO product(brandId,title) VALUES (52,'Icecream Bar - Del Monte');
INSERT INTO product(brandId,title) VALUES (46,'Banana Turning');
INSERT INTO product(brandId,title) VALUES (36,'Initation Crab Meat');
INSERT INTO product(brandId,title) VALUES (93,'Wine - Guy Sage Touraine');
INSERT INTO product(brandId,title) VALUES (9,'The Pop Shoppe Pinapple');
INSERT INTO product(brandId,title) VALUES (35,'Chocolate - Sugar Free Semi Choc');
INSERT INTO product(brandId,title) VALUES (21,'Beans - Kidney White');
INSERT INTO product(brandId,title) VALUES (48,'Muffin - Mix - Strawberry Rhubarb');
INSERT INTO product(brandId,title) VALUES (81,'Fudge - Cream Fudge');
INSERT INTO product(brandId,title) VALUES (91,'Veal - Tenderloin, Untrimmed');
INSERT INTO product(brandId,title) VALUES (28,'Coke - Diet, 355 Ml');
INSERT INTO product(brandId,title) VALUES (93,'Rabbit - Legs');
INSERT INTO product(brandId,title) VALUES (40,'Vermacelli - Sprinkles, Assorted');
INSERT INTO product(brandId,title) VALUES (93,'Remy Red');
INSERT INTO product(brandId,title) VALUES (47,'Tequila - Sauza Silver');
INSERT INTO product(brandId,title) VALUES (44,'Prunes - Pitted');
INSERT INTO product(brandId,title) VALUES (3,'Extract - Lemon');
INSERT INTO product(brandId,title) VALUES (63,'Bread - Rolls, Rye');
INSERT INTO product(brandId,title) VALUES (44,'Juice - Orangina');
INSERT INTO product(brandId,title) VALUES (66,'Juice - Orange');
INSERT INTO product(brandId,title) VALUES (96,'Chocolate Bar - Oh Henry');
INSERT INTO product(brandId,title) VALUES (13,'Straws - Cocktale');
INSERT INTO product(brandId,title) VALUES (24,'Pastry - Raisin Muffin - Mini');
INSERT INTO product(brandId,title) VALUES (15,'Glass - Juice Clear 5oz 55005');
INSERT INTO product(brandId,title) VALUES (22,'Bagel - Everything Presliced');
INSERT INTO product(brandId,title) VALUES (22,'Wine - Cotes Du Rhone');
INSERT INTO product(brandId,title) VALUES (59,'Mushroom - Lg - Cello');
INSERT INTO product(brandId,title) VALUES (73,'Chef Hat 20cm');
INSERT INTO product(brandId,title) VALUES (11,'Gin - Gilbeys London, Dry');
INSERT INTO product(brandId,title) VALUES (27,'Anisette - Mcguiness');
INSERT INTO product(brandId,title) VALUES (43,'Pasta - Spaghetti, Dry');
INSERT INTO product(brandId,title) VALUES (55,'Coffee - Espresso');
INSERT INTO product(brandId,title) VALUES (81,'Food Colouring - Green');
INSERT INTO product(brandId,title) VALUES (20,'Pepper - Scotch Bonnet');
INSERT INTO product(brandId,title) VALUES (85,'Triple Sec - Mcguinness');
INSERT INTO product(brandId,title) VALUES (67,'Crab - Back Fin Meat, Canned');
INSERT INTO product(brandId,title) VALUES (83,'Mousse - Mango');
INSERT INTO product(brandId,title) VALUES (63,'Squid - Breaded');
INSERT INTO product(brandId,title) VALUES (97,'Chocolate - Compound Coating');
INSERT INTO product(brandId,title) VALUES (24,'Bread - Hot Dog Buns');
INSERT INTO product(brandId,title) VALUES (93,'Chevril');
INSERT INTO product(brandId,title) VALUES (61,'Tea - Camomele');
INSERT INTO product(brandId,title) VALUES (20,'Beer - Moosehead');
INSERT INTO product(brandId,title) VALUES (99,'Mushroom - Porcini, Dry');
INSERT INTO product(brandId,title) VALUES (81,'Sobe - Orange Carrot');
INSERT INTO product(brandId,title) VALUES (55,'Soup - Knorr, Country Bean');
INSERT INTO product(brandId,title) VALUES (31,'Salt - Table');
INSERT INTO product(brandId,title) VALUES (17,'Halibut - Fletches');
INSERT INTO product(brandId,title) VALUES (87,'Energy - Boo - Koo');
INSERT INTO product(brandId,title) VALUES (22,'Swiss Chard');
INSERT INTO product(brandId,title) VALUES (95,'Chocolate - Semi Sweet, Calets');
INSERT INTO product(brandId,title) VALUES (39,'Pork Salted Bellies');
INSERT INTO product(brandId,title) VALUES (54,'Plastic Arrow Stir Stick');
INSERT INTO product(brandId,title) VALUES (83,'Cups 10oz Trans');
INSERT INTO product(brandId,title) VALUES (31,'Flower - Leather Leaf Fern');
INSERT INTO product(brandId,title) VALUES (31,'Pork - Caul Fat');
INSERT INTO product(brandId,title) VALUES (61,'Pork - Loin, Boneless');
INSERT INTO product(brandId,title) VALUES (8,'Juice - Propel Sport');
INSERT INTO product(brandId,title) VALUES (89,'Beer - Pilsner Urquell');
INSERT INTO product(brandId,title) VALUES (47,'Buffalo - Striploin');
INSERT INTO product(brandId,title) VALUES (62,'Shrimp - Prawn');
INSERT INTO product(brandId,title) VALUES (68,'Bread - Roll, Calabrese');
INSERT INTO product(brandId,title) VALUES (60,'Syrup - Monin - Passion Fruit');
INSERT INTO product(brandId,title) VALUES (55,'Straw - Regular');
INSERT INTO product(brandId,title) VALUES (30,'Appetizer - Mini Egg Roll, Shrimp');
INSERT INTO product(brandId,title) VALUES (87,'Vinegar - Champagne');
INSERT INTO product(brandId,title) VALUES (77,'Cumin - Whole');
INSERT INTO product(brandId,title) VALUES (83,'Bouq All Italian - Primerba');
INSERT INTO product(brandId,title) VALUES (63,'Salmon - Atlantic, No Skin');
INSERT INTO product(brandId,title) VALUES (98,'Cognac - Courvaisier');
INSERT INTO product(brandId,title) VALUES (9,'Oil - Cooking Spray');
INSERT INTO product(brandId,title) VALUES (55,'Oil - Sunflower');
INSERT INTO product(brandId,title) VALUES (77,'Coffee Cup 12oz 5342cd');
INSERT INTO product(brandId,title) VALUES (56,'Macaroons - Two Bite Choc');
INSERT INTO product(brandId,title) VALUES (66,'Seedlings - Buckwheat, Organic');
INSERT INTO product(brandId,title) VALUES (47,'Peas - Pigeon, Dry');
INSERT INTO product(brandId,title) VALUES (66,'Foam Espresso Cup Plain White');
INSERT INTO product(brandId,title) VALUES (81,'Beans - Butter Lrg Lima');
INSERT INTO product(brandId,title) VALUES (84,'Bread - Mini Hamburger Bun');
INSERT INTO product(brandId,title) VALUES (39,'Veal - Brisket, Provimi,bnls');
INSERT INTO product(brandId,title) VALUES (49,'Tomatoes Tear Drop Yellow');
INSERT INTO product(brandId,title) VALUES (26,'Shrimp - Black Tiger 13/15');
INSERT INTO product(brandId,title) VALUES (27,'Bread - Italian Roll With Herbs');
INSERT INTO product(brandId,title) VALUES (59,'Samosa - Veg');
INSERT INTO product(brandId,title) VALUES (49,'Beans - Butter Lrg Lima');
INSERT INTO product(brandId,title) VALUES (84,'Crackers - Water');
INSERT INTO product(brandId,title) VALUES (90,'Tea - Black Currant');
INSERT INTO product(brandId,title) VALUES (9,'Beef - Diced');
INSERT INTO product(brandId,title) VALUES (74,'Lettuce Romaine Chopped');
INSERT INTO product(brandId,title) VALUES (95,'Cheese - Ricotta');
INSERT INTO product(brandId,title) VALUES (33,'Pasta - Rotini, Dry');
INSERT INTO product(brandId,title) VALUES (36,'Oil - Shortening,liqud, Fry');
INSERT INTO product(brandId,title) VALUES (64,'Milk - Chocolate 250 Ml');
INSERT INTO product(brandId,title) VALUES (83,'Bread - Roll, Italian');
INSERT INTO product(brandId,title) VALUES (97,'Bread - Pullman, Sliced');
INSERT INTO product(brandId,title) VALUES (68,'Brocolinni - Gaylan, Chinese');
INSERT INTO product(brandId,title) VALUES (65,'Squash - Pepper');
INSERT INTO product(brandId,title) VALUES (24,'Plaintain');
INSERT INTO product(brandId,title) VALUES (62,'Red Currant Jelly');
INSERT INTO product(brandId,title) VALUES (9,'Wine - Red, Concha Y Toro');
INSERT INTO product(brandId,title) VALUES (32,'Cod - Black Whole Fillet');
INSERT INTO product(brandId,title) VALUES (56,'Muffin Chocolate Individual Wrap');
INSERT INTO product(brandId,title) VALUES (23,'Table Cloth 53x53 White');
INSERT INTO product(brandId,title) VALUES (98,'Wine - Pinot Grigio Collavini');
INSERT INTO product(brandId,title) VALUES (57,'Squid - U 5');
INSERT INTO product(brandId,title) VALUES (53,'Ham - Cooked Bayonne Tinned');
INSERT INTO product(brandId,title) VALUES (57,'Ice Cream - Vanilla');
INSERT INTO product(brandId,title) VALUES (100,'Creme De Menth - White');
INSERT INTO product(brandId,title) VALUES (91,'Cape Capensis - Fillet');
INSERT INTO product(brandId,title) VALUES (69,'Bacon Strip Precooked');
INSERT INTO product(brandId,title) VALUES (37,'Emulsifier');
INSERT INTO product(brandId,title) VALUES (75,'Dill Weed - Dry');
INSERT INTO product(brandId,title) VALUES (95,'Rabbit - Legs');
INSERT INTO product(brandId,title) VALUES (18,'Seaweed Green Sheets');
INSERT INTO product(brandId,title) VALUES (70,'Noodles - Cellophane, Thin');
INSERT INTO product(brandId,title) VALUES (8,'Pork - Sausage Casing');
INSERT INTO product(brandId,title) VALUES (17,'Oil - Macadamia');
INSERT INTO product(brandId,title) VALUES (40,'Mudslide');
INSERT INTO product(brandId,title) VALUES (28,'Mushrooms - Honey');
INSERT INTO product(brandId,title) VALUES (3,'Jam - Raspberry,jar');
INSERT INTO product(brandId,title) VALUES (29,'Tart - Lemon');
INSERT INTO product(brandId,title) VALUES (6,'Soup Campbells Beef With Veg');
INSERT INTO product(brandId,title) VALUES (71,'Tuna - Salad Premix');
INSERT INTO product(brandId,title) VALUES (71,'Cumin - Whole');
INSERT INTO product(brandId,title) VALUES (18,'Cookies - Englishbay Oatmeal');
INSERT INTO product(brandId,title) VALUES (78,'Shrimp - Black Tiger 13/15');
INSERT INTO product(brandId,title) VALUES (96,'Nut - Almond, Blanched, Sliced');
INSERT INTO product(brandId,title) VALUES (5,'Pur Source');
INSERT INTO product(brandId,title) VALUES (29,'Oil - Truffle, Black');
INSERT INTO product(brandId,title) VALUES (36,'Flour - Strong Pizza');
INSERT INTO product(brandId,title) VALUES (92,'Bagelers');
INSERT INTO product(brandId,title) VALUES (68,'Tomatoes - Heirloom');
INSERT INTO product(brandId,title) VALUES (17,'The Pop Shoppe - Black Cherry');
INSERT INTO product(brandId,title) VALUES (65,'Gherkin');
INSERT INTO product(brandId,title) VALUES (65,'Crackers - Trio');
INSERT INTO product(brandId,title) VALUES (76,'Bread - French Baquette');
INSERT INTO product(brandId,title) VALUES (77,'Wine - Red, Marechal Foch');
INSERT INTO product(brandId,title) VALUES (48,'Bar Nature Valley');
INSERT INTO product(brandId,title) VALUES (57,'Potato - Sweet');
INSERT INTO product(brandId,title) VALUES (7,'Cheese - Gorgonzola');
INSERT INTO product(brandId,title) VALUES (31,'Versatainer Nc - 8288');
INSERT INTO product(brandId,title) VALUES (45,'Ice Cream Bar - Drumstick');
INSERT INTO product(brandId,title) VALUES (69,'Cherries - Fresh');
INSERT INTO product(brandId,title) VALUES (13,'Wine - Segura Viudas Aria Brut');
INSERT INTO product(brandId,title) VALUES (52,'Spinach - Baby');
INSERT INTO product(brandId,title) VALUES (2,'Wine - Charddonnay Errazuriz');
INSERT INTO product(brandId,title) VALUES (77,'Bread - Bistro White');
INSERT INTO product(brandId,title) VALUES (75,'Sauce - Thousand Island');
INSERT INTO product(brandId,title) VALUES (39,'Sour Puss Sour Apple');
INSERT INTO product(brandId,title) VALUES (18,'Ostrich - Prime Cut');
INSERT INTO product(brandId,title) VALUES (95,'Nutmeg - Ground');
INSERT INTO product(brandId,title) VALUES (69,'Quiche Assorted');
INSERT INTO product(brandId,title) VALUES (1,'Dried Cranberries');
INSERT INTO product(brandId,title) VALUES (66,'Numi - Assorted Teas');
INSERT INTO product(brandId,title) VALUES (60,'Pastry - Baked Cinnamon Stick');
INSERT INTO product(brandId,title) VALUES (8,'Breakfast Quesadillas');
INSERT INTO product(brandId,title) VALUES (45,'Sobe - Orange Carrot');
INSERT INTO product(brandId,title) VALUES (21,'Juice - Apple 284ml');
INSERT INTO product(brandId,title) VALUES (19,'Tea - English Breakfast');
INSERT INTO product(brandId,title) VALUES (13,'Cheese - Brie');
INSERT INTO product(brandId,title) VALUES (79,'Cookies - Fortune');
INSERT INTO product(brandId,title) VALUES (41,'Wine - Chianti Classica Docg');
INSERT INTO product(brandId,title) VALUES (68,'Nestea - Iced Tea');
INSERT INTO product(brandId,title) VALUES (82,'Vermacelli - Sprinkles, Assorted');
INSERT INTO product(brandId,title) VALUES (50,'Muffin Mix - Corn Harvest');
INSERT INTO product(brandId,title) VALUES (39,'Cheese - Le Cheve Noir');
INSERT INTO product(brandId,title) VALUES (10,'Vinegar - Cider');
INSERT INTO product(brandId,title) VALUES (58,'Cardamon Ground');
INSERT INTO product(brandId,title) VALUES (13,'Extract - Rum');
INSERT INTO product(brandId,title) VALUES (25,'Pea - Snow');
INSERT INTO product(brandId,title) VALUES (5,'Bread - Raisin');
INSERT INTO product(brandId,title) VALUES (32,'Chinese Foods - Plain Fried Rice');
INSERT INTO product(brandId,title) VALUES (31,'Bread - Bistro Sour');
INSERT INTO product(brandId,title) VALUES (83,'Cherries - Maraschino,jar');
INSERT INTO product(brandId,title) VALUES (64,'Fuji Apples');
INSERT INTO product(brandId,title) VALUES (3,'The Pop Shoppe - Grape');
INSERT INTO product(brandId,title) VALUES (41,'Macaroons - Two Bite Choc');
INSERT INTO product(brandId,title) VALUES (67,'Longos - Burritos');
INSERT INTO product(brandId,title) VALUES (86,'Wine - Kwv Chenin Blanc South');
INSERT INTO product(brandId,title) VALUES (84,'Pastry - Mini French Pastries');
INSERT INTO product(brandId,title) VALUES (51,'Oil - Olive');
INSERT INTO product(brandId,title) VALUES (5,'Kahlua');
INSERT INTO product(brandId,title) VALUES (93,'Scallops - 20/30');
INSERT INTO product(brandId,title) VALUES (48,'Plums - Red');
INSERT INTO product(brandId,title) VALUES (18,'Table Cloth 81x81 White');
INSERT INTO product(brandId,title) VALUES (47,'Goldschalger');
INSERT INTO product(brandId,title) VALUES (38,'Napkin White - Starched');
INSERT INTO product(brandId,title) VALUES (93,'Wine - Shiraz Wolf Blass Premium');
INSERT INTO product(brandId,title) VALUES (82,'Muffin Batt - Choc Chk');
INSERT INTO product(brandId,title) VALUES (45,'Canada Dry');
INSERT INTO product(brandId,title) VALUES (41,'Soup - Knorr, Classic Can. Chili');
INSERT INTO product(brandId,title) VALUES (52,'Muffin Hinge - 211n');
INSERT INTO product(brandId,title) VALUES (66,'Energy Drink Red Bull');
INSERT INTO product(brandId,title) VALUES (81,'Dill Weed - Fresh');
INSERT INTO product(brandId,title) VALUES (46,'Squeeze Bottle');
INSERT INTO product(brandId,title) VALUES (64,'Water - San Pellegrino');
INSERT INTO product(brandId,title) VALUES (59,'Soup - Knorr, Veg / Beef');
INSERT INTO product(brandId,title) VALUES (56,'Myers Planters Punch');
INSERT INTO product(brandId,title) VALUES (59,'Carbonated Water - Cherry');
INSERT INTO product(brandId,title) VALUES (72,'Nantucket - Kiwi Berry Cktl.');
INSERT INTO product(brandId,title) VALUES (12,'Chivas Regal - 12 Year Old');
INSERT INTO product(brandId,title) VALUES (19,'Bar Special K');
INSERT INTO product(brandId,title) VALUES (31,'Wine - Piper Heidsieck Brut');
INSERT INTO product(brandId,title) VALUES (21,'Aspic - Amber');
INSERT INTO product(brandId,title) VALUES (69,'Versatainer Nc - 8288');
INSERT INTO product(brandId,title) VALUES (27,'Coffee Beans - Chocolate');
INSERT INTO product(brandId,title) VALUES (8,'Langers - Cranberry Cocktail');
INSERT INTO product(brandId,title) VALUES (17,'Cheese - St. Paulin');
INSERT INTO product(brandId,title) VALUES (42,'Muffin - Blueberry Individual');
INSERT INTO product(brandId,title) VALUES (32,'Pasta - Rotini, Dry');
INSERT INTO product(brandId,title) VALUES (30,'Veal - Slab Bacon');
INSERT INTO product(brandId,title) VALUES (6,'Soup - Verve - Chipotle Chicken');
INSERT INTO product(brandId,title) VALUES (71,'Strawberries');
INSERT INTO product(brandId,title) VALUES (33,'Wine - Taylors Reserve');
INSERT INTO product(brandId,title) VALUES (95,'Crab - Claws, 26 - 30');
INSERT INTO product(brandId,title) VALUES (97,'Oil - Olive Bertolli');
INSERT INTO product(brandId,title) VALUES (62,'Bananas');
INSERT INTO product(brandId,title) VALUES (6,'Flour Dark Rye');
INSERT INTO product(brandId,title) VALUES (31,'Clam - Cherrystone');
INSERT INTO product(brandId,title) VALUES (2,'Pasta - Canelloni');
INSERT INTO product(brandId,title) VALUES (13,'Wine - White, Riesling, Semi - Dry');
INSERT INTO product(brandId,title) VALUES (39,'Rosemary - Primerba, Paste');
INSERT INTO product(brandId,title) VALUES (32,'Monkfish Fresh - Skin Off');
INSERT INTO product(brandId,title) VALUES (30,'Chips Potato Swt Chilli Sour');
INSERT INTO product(brandId,title) VALUES (35,'Muffin - Mix - Strawberry Rhubarb');
INSERT INTO product(brandId,title) VALUES (35,'Bread Sour Rolls');
INSERT INTO product(brandId,title) VALUES (67,'Juice - Propel Sport');
INSERT INTO product(brandId,title) VALUES (93,'Carrots - Mini, Stem On');
INSERT INTO product(brandId,title) VALUES (11,'Truffle Cups - Red');
INSERT INTO product(brandId,title) VALUES (72,'Cheese - Le Cru Du Clocher');
INSERT INTO product(brandId,title) VALUES (70,'Olives - Green, Pitted');
INSERT INTO product(brandId,title) VALUES (2,'Pork - Caul Fat');
INSERT INTO product(brandId,title) VALUES (54,'Aspic - Light');
INSERT INTO product(brandId,title) VALUES (57,'Bread - Bagels, Plain');
INSERT INTO product(brandId,title) VALUES (81,'Pasta - Cheese / Spinach Bauletti');
INSERT INTO product(brandId,title) VALUES (73,'Flavouring - Orange');
INSERT INTO product(brandId,title) VALUES (77,'Worcestershire Sauce');
INSERT INTO product(brandId,title) VALUES (68,'Towel Dispenser');
INSERT INTO product(brandId,title) VALUES (26,'Red Currant Jelly');
INSERT INTO product(brandId,title) VALUES (99,'Wine - Rioja Campo Viejo');
INSERT INTO product(brandId,title) VALUES (23,'Pan Grease');
INSERT INTO product(brandId,title) VALUES (69,'Muffin Mix - Corn Harvest');
INSERT INTO product(brandId,title) VALUES (29,'Rice - Brown');
INSERT INTO product(brandId,title) VALUES (3,'Tart Shells - Savory, 3');
INSERT INTO product(brandId,title) VALUES (77,'Flour - Masa De Harina Mexican');
INSERT INTO product(brandId,title) VALUES (16,'Bread Cranberry Foccacia');
INSERT INTO product(brandId,title) VALUES (90,'Pear - Asian');
INSERT INTO product(brandId,title) VALUES (74,'Bar Special K');
INSERT INTO product(brandId,title) VALUES (85,'Pastry - Baked Scones - Mini');
INSERT INTO product(brandId,title) VALUES (9,'Wiberg Cure');
INSERT INTO product(brandId,title) VALUES (13,'Sole - Iqf');
INSERT INTO product(brandId,title) VALUES (65,'Pears - Anjou');
INSERT INTO product(brandId,title) VALUES (27,'Oil - Sesame');
INSERT INTO product(brandId,title) VALUES (28,'Olive - Spread Tapenade');
INSERT INTO product(brandId,title) VALUES (62,'Bread - Multigrain, Loaf');
INSERT INTO product(brandId,title) VALUES (47,'Chicken Giblets');
INSERT INTO product(brandId,title) VALUES (42,'Fuji Apples');
INSERT INTO product(brandId,title) VALUES (23,'Beets - Golden');
INSERT INTO product(brandId,title) VALUES (78,'Cheese - Bakers Cream Cheese');
INSERT INTO product(brandId,title) VALUES (71,'Chicken Breast Halal');
INSERT INTO product(brandId,title) VALUES (8,'Beer - Blue');
INSERT INTO product(brandId,title) VALUES (94,'Soup Campbells Mexicali Tortilla');
INSERT INTO product(brandId,title) VALUES (46,'Cheese - Swiss');
INSERT INTO product(brandId,title) VALUES (51,'Wine - White, Cooking');
INSERT INTO product(brandId,title) VALUES (6,'Sage Ground Wiberg');
INSERT INTO product(brandId,title) VALUES (24,'Pepper - Roasted Red');
INSERT INTO product(brandId,title) VALUES (16,'Beer - Moosehead');
INSERT INTO product(brandId,title) VALUES (90,'Wine - White, Ej Gallo');
INSERT INTO product(brandId,title) VALUES (32,'Rice - Brown');
INSERT INTO product(brandId,title) VALUES (94,'Sausage - Liver');
INSERT INTO product(brandId,title) VALUES (60,'Sauce - Cranberry');
INSERT INTO product(brandId,title) VALUES (47,'Food Colouring - Blue');
INSERT INTO product(brandId,title) VALUES (92,'Sherbet - Raspberry');
INSERT INTO product(brandId,title) VALUES (90,'Island Oasis - Cappucino Mix');
INSERT INTO product(brandId,title) VALUES (89,'Cheese - Parmesan Grated');
INSERT INTO product(brandId,title) VALUES (37,'Soup - Campbells, Lentil');
INSERT INTO product(brandId,title) VALUES (41,'Salami - Genova');
INSERT INTO product(brandId,title) VALUES (51,'Lighter - Bbq');
INSERT INTO product(brandId,title) VALUES (68,'Sugar - Crumb');
INSERT INTO product(brandId,title) VALUES (30,'Wine - Piper Heidsieck Brut');
INSERT INTO product(brandId,title) VALUES (57,'Juice - Happy Planet');
INSERT INTO product(brandId,title) VALUES (11,'Wine - Redchard Merritt');
INSERT INTO product(brandId,title) VALUES (29,'Lentils - Green, Dry');
INSERT INTO product(brandId,title) VALUES (54,'Sauce - Mint');
INSERT INTO product(brandId,title) VALUES (13,'Sultanas');
INSERT INTO product(brandId,title) VALUES (97,'Wine - Chateau Bonnet');
INSERT INTO product(brandId,title) VALUES (15,'Wine - Vineland Estate Semi - Dry');
INSERT INTO product(brandId,title) VALUES (2,'Sea Bass - Fillets');
INSERT INTO product(brandId,title) VALUES (30,'Turkey Leg With Drum And Thigh');
INSERT INTO product(brandId,title) VALUES (73,'Nantucket - Carrot Orange');
INSERT INTO product(brandId,title) VALUES (55,'Cheese - Oka');
INSERT INTO product(brandId,title) VALUES (90,'Lobak');
INSERT INTO product(brandId,title) VALUES (59,'Sugar - Individual Portions');
INSERT INTO product(brandId,title) VALUES (68,'Beef - Diced');
INSERT INTO product(brandId,title) VALUES (43,'Foil - 4oz Custard Cup');
INSERT INTO product(brandId,title) VALUES (97,'Beans - Long, Chinese');
INSERT INTO product(brandId,title) VALUES (6,'Beef - Texas Style Burger');
INSERT INTO product(brandId,title) VALUES (26,'Mustard - Dry, Powder');
INSERT INTO product(brandId,title) VALUES (48,'Yeast Dry - Fleischman');
INSERT INTO product(brandId,title) VALUES (8,'Ham Black Forest');
INSERT INTO product(brandId,title) VALUES (42,'Pancetta');
INSERT INTO product(brandId,title) VALUES (96,'Sultanas');
INSERT INTO product(brandId,title) VALUES (79,'Cookies Cereal Nut');
INSERT INTO product(brandId,title) VALUES (82,'Flour - Strong Pizza');
INSERT INTO product(brandId,title) VALUES (49,'Veal - Round, Eye Of');
INSERT INTO product(brandId,title) VALUES (76,'Rice - 7 Grain Blend');
INSERT INTO product(brandId,title) VALUES (90,'Cheese - Cheddarsliced');
INSERT INTO product(brandId,title) VALUES (30,'Pastry - Trippleberry Muffin - Mini');
INSERT INTO product(brandId,title) VALUES (10,'Flour - Masa De Harina Mexican');
INSERT INTO product(brandId,title) VALUES (7,'Potatoes - Yukon Gold 5 Oz');
INSERT INTO product(brandId,title) VALUES (30,'Soup - Campbells - Chicken Noodle');
INSERT INTO product(brandId,title) VALUES (4,'Tea - Darjeeling, Azzura');
INSERT INTO product(brandId,title) VALUES (84,'Gatorade - Lemon Lime');
INSERT INTO product(brandId,title) VALUES (16,'Alize Sunset');
INSERT INTO product(brandId,title) VALUES (14,'Beef - Ox Tongue');
INSERT INTO product(brandId,title) VALUES (81,'Beef - Kindney, Whole');
INSERT INTO product(brandId,title) VALUES (22,'Muffin - Banana Nut Individual');
INSERT INTO product(brandId,title) VALUES (44,'Cranberries - Frozen');
INSERT INTO product(brandId,title) VALUES (33,'Onion Powder');
INSERT INTO product(brandId,title) VALUES (42,'Cheese - Oka');
INSERT INTO product(brandId,title) VALUES (35,'Aspic - Light');
INSERT INTO product(brandId,title) VALUES (17,'Wine - Prosecco Valdobiaddene');
INSERT INTO product(brandId,title) VALUES (23,'Sugar Thermometer');
INSERT INTO product(brandId,title) VALUES (54,'Turkey - Breast, Double');
INSERT INTO product(brandId,title) VALUES (81,'Chicken - Wieners');
INSERT INTO product(brandId,title) VALUES (69,'Container - Clear 16 Oz');
INSERT INTO product(brandId,title) VALUES (69,'Puree - Kiwi');
INSERT INTO product(brandId,title) VALUES (33,'Mix Pina Colada');
INSERT INTO product(brandId,title) VALUES (67,'Miso Paste White');
INSERT INTO product(brandId,title) VALUES (33,'Pickerel - Fillets');
INSERT INTO product(brandId,title) VALUES (70,'Pasta - Rotini, Dry');
INSERT INTO product(brandId,title) VALUES (9,'Trueblue - Blueberry');
INSERT INTO product(brandId,title) VALUES (45,'Pork - Ground');
INSERT INTO product(brandId,title) VALUES (96,'Wood Chips - Regular');
INSERT INTO product(brandId,title) VALUES (72,'Kale - Red');
INSERT INTO product(brandId,title) VALUES (55,'The Pop Shoppe - Lime Rickey');
INSERT INTO product(brandId,title) VALUES (52,'Nectarines');
INSERT INTO product(brandId,title) VALUES (78,'Wiberg Cure');
INSERT INTO product(brandId,title) VALUES (87,'Fish - Scallops, Cold Smoked');
INSERT INTO product(brandId,title) VALUES (69,'Browning Caramel Glace');
INSERT INTO product(brandId,title) VALUES (2,'Rice Paper');
INSERT INTO product(brandId,title) VALUES (12,'Onions - Green');
INSERT INTO product(brandId,title) VALUES (76,'Oil - Canola');
INSERT INTO product(brandId,title) VALUES (99,'Flower - Potmums');
INSERT INTO product(brandId,title) VALUES (75,'Pastry - Apple Large');
INSERT INTO product(brandId,title) VALUES (8,'Soup - Knorr, Country Bean');
INSERT INTO product(brandId,title) VALUES (58,'Vermacelli - Sprinkles, Assorted');
INSERT INTO product(brandId,title) VALUES (34,'Ham - Cooked Bayonne Tinned');
INSERT INTO product(brandId,title) VALUES (10,'Mangostein');
INSERT INTO product(brandId,title) VALUES (78,'Soup - Campbells, Creamy');
INSERT INTO product(brandId,title) VALUES (1,'Eggwhite Frozen');
INSERT INTO product(brandId,title) VALUES (71,'Bacon Strip Precooked');
INSERT INTO product(brandId,title) VALUES (15,'Tart - Butter Plain Squares');
INSERT INTO product(brandId,title) VALUES (37,'Sprouts - China Rose');
INSERT INTO product(brandId,title) VALUES (9,'Cheese - Bakers Cream Cheese');
INSERT INTO product(brandId,title) VALUES (56,'Beef - Eye Of Round');
INSERT INTO product(brandId,title) VALUES (98,'Artichoke - Fresh');
INSERT INTO product(brandId,title) VALUES (75,'Syrup - Monin - Blue Curacao');
INSERT INTO product(brandId,title) VALUES (20,'Nestea - Ice Tea, Diet');
INSERT INTO product(brandId,title) VALUES (91,'Russian Prince');
INSERT INTO product(brandId,title) VALUES (94,'Yogurt - Banana, 175 Gr');
INSERT INTO product(brandId,title) VALUES (47,'Carrots - Mini Red Organic');
INSERT INTO product(brandId,title) VALUES (12,'Muffin Orange Individual');
INSERT INTO product(brandId,title) VALUES (63,'Orange Roughy 4/6 Oz');
INSERT INTO product(brandId,title) VALUES (60,'Pasta - Rotini, Dry');
INSERT INTO product(brandId,title) VALUES (13,'Wine - Beringer Founders Estate');
INSERT INTO product(brandId,title) VALUES (33,'Yogurt - Raspberry, 175 Gr');
INSERT INTO product(brandId,title) VALUES (38,'Grapes - Black');
INSERT INTO product(brandId,title) VALUES (67,'Russian Prince');
INSERT INTO product(brandId,title) VALUES (18,'Coconut Milk - Unsweetened');
INSERT INTO product(brandId,title) VALUES (35,'Gin - Gilbeys London, Dry');
INSERT INTO product(brandId,title) VALUES (95,'Bagel - 12 Grain Preslice');
INSERT INTO product(brandId,title) VALUES (43,'Scallops - In Shell');
INSERT INTO product(brandId,title) VALUES (35,'Scallops - U - 10');
INSERT INTO product(brandId,title) VALUES (35,'Rice - 7 Grain Blend');
INSERT INTO product(brandId,title) VALUES (89,'Oyster - In Shell');
INSERT INTO product(brandId,title) VALUES (46,'Bread - Sour Sticks With Onion');
INSERT INTO product(brandId,title) VALUES (76,'Salmon - Whole, 4 - 6 Pounds');
INSERT INTO product(brandId,title) VALUES (22,'Wine - Red, Lurton Merlot De');
INSERT INTO product(brandId,title) VALUES (96,'Pears - Bosc');
INSERT INTO product(brandId,title) VALUES (19,'Coffee Cup 12oz 5342cd');
INSERT INTO product(brandId,title) VALUES (81,'Beer - Blue');
INSERT INTO product(brandId,title) VALUES (43,'Smirnoff Green Apple Twist');
INSERT INTO product(brandId,title) VALUES (81,'Icecream - Dibs');
INSERT INTO product(brandId,title) VALUES (12,'Milk - 2% 250 Ml');
INSERT INTO product(brandId,title) VALUES (96,'Table Cloth 54x54 Colour');
INSERT INTO product(brandId,title) VALUES (17,'Foil Cont Round');
INSERT INTO product(brandId,title) VALUES (54,'Cinnamon - Stick');
INSERT INTO product(brandId,title) VALUES (59,'V8 - Tropical Blend');
INSERT INTO product(brandId,title) VALUES (55,'Pasta - Agnolotti - Butternut');
INSERT INTO product(brandId,title) VALUES (83,'Bagel - Whole White Sesame');
INSERT INTO product(brandId,title) VALUES (62,'Island Oasis - Cappucino Mix');
INSERT INTO product(brandId,title) VALUES (35,'Ocean Spray - Kiwi Strawberry');
INSERT INTO product(brandId,title) VALUES (66,'Soup - Campbells');
INSERT INTO product(brandId,title) VALUES (15,'Coffee - Flavoured');
INSERT INTO product(brandId,title) VALUES (3,'Chef Hat 25cm');
INSERT INTO product(brandId,title) VALUES (84,'Rabbit - Whole');
INSERT INTO product(brandId,title) VALUES (7,'Puree - Raspberry');
INSERT INTO product(brandId,title) VALUES (82,'Cookie Double Choco');
INSERT INTO product(brandId,title) VALUES (19,'Ham Black Forest');
INSERT INTO product(brandId,title) VALUES (35,'Everfresh Products');
INSERT INTO product(brandId,title) VALUES (26,'Juice - Mango');
INSERT INTO product(brandId,title) VALUES (9,'Broom - Angled');
INSERT INTO product(brandId,title) VALUES (49,'Gherkin');
INSERT INTO product(brandId,title) VALUES (76,'Wine - Red, Gamay Noir');
INSERT INTO product(brandId,title) VALUES (90,'Tart - Lemon');
INSERT INTO product(brandId,title) VALUES (28,'Beer - True North Strong Ale');
INSERT INTO product(brandId,title) VALUES (86,'Honey - Comb');
INSERT INTO product(brandId,title) VALUES (53,'Pepper - White, Ground');
INSERT INTO product(brandId,title) VALUES (57,'Squash - Sunburst');
INSERT INTO product(brandId,title) VALUES (25,'Clam - Cherrystone');
INSERT INTO product(brandId,title) VALUES (49,'Rice - Brown');
INSERT INTO product(brandId,title) VALUES (83,'Eggroll');
INSERT INTO product(brandId,title) VALUES (79,'Brandy - Bar');
INSERT INTO product(brandId,title) VALUES (12,'Pastry - Chocolate Marble Tea');
INSERT INTO product(brandId,title) VALUES (15,'Syrup - Kahlua Chocolate');
INSERT INTO product(brandId,title) VALUES (42,'Corn Syrup');
INSERT INTO product(brandId,title) VALUES (89,'Quail - Whole, Bone - In');
INSERT INTO product(brandId,title) VALUES (19,'Arctic Char - Fillets');
INSERT INTO product(brandId,title) VALUES (23,'Shrimp - Baby, Warm Water');
INSERT INTO product(brandId,title) VALUES (20,'Sobe - Orange Carrot');
INSERT INTO product(brandId,title) VALUES (45,'Beef - Kobe Striploin');
INSERT INTO product(brandId,title) VALUES (71,'Veal - Brisket, Provimi,bnls');
INSERT INTO product(brandId,title) VALUES (88,'Wine - German Riesling');
INSERT INTO product(brandId,title) VALUES (22,'Pasta - Tortellini, Fresh');
INSERT INTO product(brandId,title) VALUES (43,'Cup - 8oz Coffee Perforated');
INSERT INTO product(brandId,title) VALUES (77,'Table Cloth 90x90 White');
INSERT INTO product(brandId,title) VALUES (10,'Wine - Chateau Aqueria Tavel');
INSERT INTO product(brandId,title) VALUES (13,'Cheese - Camembert');
INSERT INTO product(brandId,title) VALUES (11,'Puff Pastry - Sheets');
INSERT INTO product(brandId,title) VALUES (72,'Kiwi');
INSERT INTO product(brandId,title) VALUES (47,'Grand Marnier');
INSERT INTO product(brandId,title) VALUES (73,'Wine - Fontanafredda Barolo');
INSERT INTO product(brandId,title) VALUES (42,'Cake Circle, Foil, Scallop');
INSERT INTO product(brandId,title) VALUES (61,'Chicken - Whole Roasting');
INSERT INTO product(brandId,title) VALUES (92,'Sage - Ground');
INSERT INTO product(brandId,title) VALUES (83,'Oil - Margarine');
INSERT INTO product(brandId,title) VALUES (62,'Bread - Bagels, Plain');
INSERT INTO product(brandId,title) VALUES (24,'Bag - Regular Kraft 20 Lb');
INSERT INTO product(brandId,title) VALUES (33,'Pastry - Plain Baked Croissant');
INSERT INTO product(brandId,title) VALUES (61,'Spice - Paprika');
INSERT INTO product(brandId,title) VALUES (25,'Apple - Fuji');
INSERT INTO product(brandId,title) VALUES (15,'Crackers - Trio');
INSERT INTO product(brandId,title) VALUES (5,'Cake - Mini Potato Pancake');
INSERT INTO product(brandId,title) VALUES (16,'Wine - Red, Mouton Cadet');
INSERT INTO product(brandId,title) VALUES (7,'Lamb - Whole Head Off');
INSERT INTO product(brandId,title) VALUES (27,'Mustard - Dijon');
INSERT INTO product(brandId,title) VALUES (54,'Truffle Paste');
INSERT INTO product(brandId,title) VALUES (80,'Oil - Pumpkinseed');
INSERT INTO product(brandId,title) VALUES (40,'Syrup - Monin - Passion Fruit');
INSERT INTO product(brandId,title) VALUES (56,'Beef - Cooked, Corned');
INSERT INTO product(brandId,title) VALUES (40,'Rum - Mount Gay Eclipes');
INSERT INTO product(brandId,title) VALUES (34,'Potatoes - Peeled');
INSERT INTO product(brandId,title) VALUES (22,'Grand Marnier');
INSERT INTO product(brandId,title) VALUES (87,'Cinnamon Buns Sticky');
INSERT INTO product(brandId,title) VALUES (91,'Shrimp - Prawn');
INSERT INTO product(brandId,title) VALUES (97,'Cream - 18%');
INSERT INTO product(brandId,title) VALUES (77,'Wine - Penfolds Koonuga Hill');
INSERT INTO product(brandId,title) VALUES (82,'Bread - Rolls, Corn');
INSERT INTO product(brandId,title) VALUES (73,'Lettuce - Arugula');
INSERT INTO product(brandId,title) VALUES (16,'Croissant, Raw - Mini');
INSERT INTO product(brandId,title) VALUES (85,'Mousse - Mango');
INSERT INTO product(brandId,title) VALUES (49,'Beans - Yellow');
INSERT INTO product(brandId,title) VALUES (67,'Orange - Tangerine');
INSERT INTO product(brandId,title) VALUES (94,'Cornflakes');
INSERT INTO product(brandId,title) VALUES (45,'Tortillas - Flour, 8');
INSERT INTO product(brandId,title) VALUES (46,'Saskatoon Berries - Frozen');
INSERT INTO product(brandId,title) VALUES (91,'Wine - Segura Viudas Aria Brut');
INSERT INTO product(brandId,title) VALUES (38,'Food Colouring - Pink');
INSERT INTO product(brandId,title) VALUES (81,'Wine - Chianti Classica Docg');
INSERT INTO product(brandId,title) VALUES (36,'Flour - Whole Wheat');
INSERT INTO product(brandId,title) VALUES (82,'Pepper - Green');
INSERT INTO product(brandId,title) VALUES (64,'Tuna - Yellowfin');
INSERT INTO product(brandId,title) VALUES (82,'Marjoram - Dried, Rubbed');
INSERT INTO product(brandId,title) VALUES (28,'Soap - Mr.clean Floor Soap');
INSERT INTO product(brandId,title) VALUES (71,'Cookie Dough - Double');
INSERT INTO product(brandId,title) VALUES (32,'Flour - Strong Pizza');
INSERT INTO product(brandId,title) VALUES (40,'Chip - Potato Dill Pickle');
INSERT INTO product(brandId,title) VALUES (73,'Sage - Fresh');
INSERT INTO product(brandId,title) VALUES (42,'Oyster - In Shell');
INSERT INTO product(brandId,title) VALUES (35,'Ice Cream Bar - Drumstick');
INSERT INTO product(brandId,title) VALUES (29,'Calaloo');
INSERT INTO product(brandId,title) VALUES (17,'Sage - Fresh');
INSERT INTO product(brandId,title) VALUES (21,'Lamb - Leg, Diced');
INSERT INTO product(brandId,title) VALUES (59,'Soda Water - Club Soda, 355 Ml');
INSERT INTO product(brandId,title) VALUES (78,'Basil - Primerba, Paste');
INSERT INTO product(brandId,title) VALUES (19,'Bread - Italian Sesame Poly');
INSERT INTO product(brandId,title) VALUES (44,'Liners - Banana, Paper');
INSERT INTO product(brandId,title) VALUES (77,'Cheese - Cheddar, Old White');
INSERT INTO product(brandId,title) VALUES (38,'Apple - Delicious, Red');
INSERT INTO product(brandId,title) VALUES (70,'Tomatoes - Hot House');
INSERT INTO product(brandId,title) VALUES (80,'Puff Pastry - Slab');
INSERT INTO product(brandId,title) VALUES (74,'Flour - Bran, Red');
INSERT INTO product(brandId,title) VALUES (31,'Lychee');
INSERT INTO product(brandId,title) VALUES (63,'Maple Syrup');
INSERT INTO product(brandId,title) VALUES (38,'Island Oasis - Peach Daiquiri');
INSERT INTO product(brandId,title) VALUES (77,'Country Roll');
INSERT INTO product(brandId,title) VALUES (1,'Sauce - Gravy, Au Jus, Mix');
INSERT INTO product(brandId,title) VALUES (38,'Crush - Cream Soda');
INSERT INTO product(brandId,title) VALUES (64,'Dc - Sakura Fu');
INSERT INTO product(brandId,title) VALUES (8,'Yucca');
INSERT INTO product(brandId,title) VALUES (64,'Cod - Black Whole Fillet');
INSERT INTO product(brandId,title) VALUES (75,'Sobe - Lizard Fuel');
INSERT INTO product(brandId,title) VALUES (39,'Lettuce - Boston Bib');
INSERT INTO product(brandId,title) VALUES (24,'Broom And Brush Rack Black');
INSERT INTO product(brandId,title) VALUES (58,'Pizza Pizza Dough');
INSERT INTO product(brandId,title) VALUES (52,'Pork - European Side Bacon');
INSERT INTO product(brandId,title) VALUES (44,'Puree - Guava');
INSERT INTO product(brandId,title) VALUES (81,'Sesame Seed');
INSERT INTO product(brandId,title) VALUES (48,'Soup Knorr Chili With Beans');
INSERT INTO product(brandId,title) VALUES (96,'Coconut - Shredded, Sweet');
INSERT INTO product(brandId,title) VALUES (11,'Danishes - Mini Cheese');
INSERT INTO product(brandId,title) VALUES (43,'Wine - White, Ej Gallo');
INSERT INTO product(brandId,title) VALUES (70,'Coffee Beans - Chocolate');
INSERT INTO product(brandId,title) VALUES (92,'Tomatoes');
INSERT INTO product(brandId,title) VALUES (36,'Cheese - Cheddarsliced');
INSERT INTO product(brandId,title) VALUES (37,'Relish');
INSERT INTO product(brandId,title) VALUES (95,'Pasta - Canelloni, Single Serve');
INSERT INTO product(brandId,title) VALUES (70,'Sweet Pea Sprouts');
INSERT INTO product(brandId,title) VALUES (61,'Bread - French Stick');
INSERT INTO product(brandId,title) VALUES (69,'Juice - Orange, 341 Ml');
INSERT INTO product(brandId,title) VALUES (53,'Truffle Shells - Semi - Sweet');
INSERT INTO product(brandId,title) VALUES (11,'Clams - Bay');
INSERT INTO product(brandId,title) VALUES (51,'Ham - Smoked, Bone - In');
INSERT INTO product(brandId,title) VALUES (36,'Lettuce - Belgian Endive');
INSERT INTO product(brandId,title) VALUES (9,'Flour - Rye');
INSERT INTO product(brandId,title) VALUES (10,'Fruit Mix - Light');
INSERT INTO product(brandId,title) VALUES (93,'Raisin - Dark');
INSERT INTO product(brandId,title) VALUES (79,'Pork - Ground');
INSERT INTO product(brandId,title) VALUES (64,'Pepper - Paprika, Spanish');
INSERT INTO product(brandId,title) VALUES (98,'Momiji Oroshi Chili Sauce');
INSERT INTO product(brandId,title) VALUES (88,'Wine - Red, Antinori Santa');
INSERT INTO product(brandId,title) VALUES (30,'Soup - Base Broth Chix');
INSERT INTO product(brandId,title) VALUES (32,'Pasta - Spaghetti, Dry');
INSERT INTO product(brandId,title) VALUES (64,'Hinge W Undercut');
INSERT INTO product(brandId,title) VALUES (24,'Bread - Petit Baguette');
INSERT INTO product(brandId,title) VALUES (76,'Beef Flat Iron Steak');
INSERT INTO product(brandId,title) VALUES (32,'Tuna - Sushi Grade');
INSERT INTO product(brandId,title) VALUES (4,'Oil - Olive');
INSERT INTO product(brandId,title) VALUES (82,'Tea - Mint');
INSERT INTO product(brandId,title) VALUES (28,'Sesame Seed');
INSERT INTO product(brandId,title) VALUES (10,'Chevril');
INSERT INTO product(brandId,title) VALUES (95,'Toothpick Frilled');
INSERT INTO product(brandId,title) VALUES (54,'Wanton Wrap');
INSERT INTO product(brandId,title) VALUES (96,'Dehydrated Kelp Kombo');
INSERT INTO product(brandId,title) VALUES (23,'Lamb - Pieces, Diced');
INSERT INTO product(brandId,title) VALUES (36,'Chicken Thigh - Bone Out');
INSERT INTO product(brandId,title) VALUES (80,'Goat - Leg');
INSERT INTO product(brandId,title) VALUES (36,'Cheese - Brie, Cups 125g');
INSERT INTO product(brandId,title) VALUES (96,'Ice Cream - Strawberry');
INSERT INTO product(brandId,title) VALUES (7,'Bag Clear 10 Lb');
INSERT INTO product(brandId,title) VALUES (79,'Chocolate Bar - Reese Pieces');
INSERT INTO product(brandId,title) VALUES (10,'Extract - Raspberry');
INSERT INTO product(brandId,title) VALUES (97,'Pepper - Scotch Bonnet');
INSERT INTO product(brandId,title) VALUES (42,'Tortillas - Flour, 10');
INSERT INTO product(brandId,title) VALUES (50,'Chips Potato Swt Chilli Sour');
INSERT INTO product(brandId,title) VALUES (48,'Appetizer - Sausage Rolls');
INSERT INTO product(brandId,title) VALUES (74,'Sage - Fresh');
INSERT INTO product(brandId,title) VALUES (61,'Chicken - Livers');
INSERT INTO product(brandId,title) VALUES (57,'Beans - Butter Lrg Lima');
INSERT INTO product(brandId,title) VALUES (50,'Roe - White Fish');
INSERT INTO product(brandId,title) VALUES (76,'Water, Tap');
INSERT INTO product(brandId,title) VALUES (20,'Toamtoes 6x7 Select');
INSERT INTO product(brandId,title) VALUES (43,'Veal - Liver');
INSERT INTO product(brandId,title) VALUES (24,'Sprouts - Corn');
INSERT INTO product(brandId,title) VALUES (93,'Jameson Irish Whiskey');
INSERT INTO product(brandId,title) VALUES (66,'Bagel - Sesame Seed Presliced');
INSERT INTO product(brandId,title) VALUES (28,'Spice - Pepper Portions');
INSERT INTO product(brandId,title) VALUES (70,'Apple - Macintosh');
INSERT INTO product(brandId,title) VALUES (12,'Marjoram - Fresh');
INSERT INTO product(brandId,title) VALUES (47,'Numi - Assorted Teas');
INSERT INTO product(brandId,title) VALUES (28,'Soup - Knorr, Country Bean');
INSERT INTO product(brandId,title) VALUES (72,'Chip - Potato Dill Pickle');
INSERT INTO product(brandId,title) VALUES (20,'Cinnamon - Stick');
INSERT INTO product(brandId,title) VALUES (11,'Wine - Cave Springs Dry Riesling');
INSERT INTO product(brandId,title) VALUES (63,'Mayonnaise');
INSERT INTO product(brandId,title) VALUES (53,'Cookies Cereal Nut');
INSERT INTO product(brandId,title) VALUES (74,'Zucchini - Green');
INSERT INTO product(brandId,title) VALUES (20,'Juice - Apple 284ml');
INSERT INTO product(brandId,title) VALUES (60,'Beer - Moosehead');
INSERT INTO product(brandId,title) VALUES (8,'Muffin - Blueberry Individual');
INSERT INTO product(brandId,title) VALUES (3,'Pork - Side Ribs');
INSERT INTO product(brandId,title) VALUES (19,'Flower - Commercial Spider');
INSERT INTO product(brandId,title) VALUES (96,'Chinese Foods - Plain Fried Rice');
INSERT INTO product(brandId,title) VALUES (30,'Corn - Mini');
INSERT INTO product(brandId,title) VALUES (8,'Tea - Green');
INSERT INTO product(brandId,title) VALUES (40,'Breadfruit');
INSERT INTO product(brandId,title) VALUES (50,'Bread - French Baquette');
INSERT INTO product(brandId,title) VALUES (81,'Flour - Rye');
INSERT INTO product(brandId,title) VALUES (6,'Berry Brulee');
INSERT INTO product(brandId,title) VALUES (94,'Cheese - Valancey');
INSERT INTO product(brandId,title) VALUES (85,'Salami - Genova');
INSERT INTO product(brandId,title) VALUES (91,'Olives - Morracan Dired');
INSERT INTO product(brandId,title) VALUES (13,'Shrimp - 16/20, Peeled Deviened');
INSERT INTO product(brandId,title) VALUES (80,'Wine - Crozes Hermitage E.');
INSERT INTO product(brandId,title) VALUES (99,'Garlic - Elephant');
INSERT INTO product(brandId,title) VALUES (34,'Yams');
INSERT INTO product(brandId,title) VALUES (21,'Sobe - Orange Carrot');
INSERT INTO product(brandId,title) VALUES (70,'Clam Nectar');
INSERT INTO product(brandId,title) VALUES (7,'Liners - Banana, Paper');
INSERT INTO product(brandId,title) VALUES (67,'Croissant, Raw - Mini');
INSERT INTO product(brandId,title) VALUES (56,'Ice Cream - Chocolate');
INSERT INTO product(brandId,title) VALUES (56,'Chocolate - Compound Coating');
INSERT INTO product(brandId,title) VALUES (78,'Bread - Sour Sticks With Onion');
INSERT INTO product(brandId,title) VALUES (8,'Artichoke - Bottom, Canned');
INSERT INTO product(brandId,title) VALUES (71,'Cotton Wet Mop 16 Oz');
INSERT INTO product(brandId,title) VALUES (16,'Rabbit - Legs');
INSERT INTO product(brandId,title) VALUES (59,'Bagels Poppyseed');
INSERT INTO product(brandId,title) VALUES (57,'Wine - Casillero Del Diablo');
INSERT INTO product(brandId,title) VALUES (51,'Olive - Spread Tapenade');
INSERT INTO product(brandId,title) VALUES (86,'Turkey - Breast, Double');
INSERT INTO product(brandId,title) VALUES (23,'Lid - High Heat, Super Clear');
INSERT INTO product(brandId,title) VALUES (22,'Coffee Cup 16oz Foam');
INSERT INTO product(brandId,title) VALUES (23,'Daikon Radish');
INSERT INTO product(brandId,title) VALUES (95,'Beans - Black Bean, Preserved');
INSERT INTO product(brandId,title) VALUES (62,'Wine - Prem Select Charddonany');
INSERT INTO product(brandId,title) VALUES (6,'Scallop - St. Jaques');
INSERT INTO product(brandId,title) VALUES (72,'Cheese - Cream Cheese');
INSERT INTO product(brandId,title) VALUES (68,'Beef - Roasted, Cooked');
INSERT INTO product(brandId,title) VALUES (90,'Juice - Clam, 46 Oz');
INSERT INTO product(brandId,title) VALUES (71,'Wine - Chateau Bonnet');
INSERT INTO product(brandId,title) VALUES (70,'Pesto - Primerba, Paste');
INSERT INTO product(brandId,title) VALUES (2,'Icecream - Dstk Strw Chseck');
INSERT INTO product(brandId,title) VALUES (1,'Water - Evian 355 Ml');
INSERT INTO product(brandId,title) VALUES (82,'Lamb - Leg, Diced');
INSERT INTO product(brandId,title) VALUES (21,'Tahini Paste');
INSERT INTO product(brandId,title) VALUES (73,'Wonton Wrappers');
INSERT INTO product(brandId,title) VALUES (11,'Soup - Clam Chowder, Dry Mix');
INSERT INTO product(brandId,title) VALUES (88,'Barramundi');
INSERT INTO product(brandId,title) VALUES (25,'Rosemary - Fresh');
INSERT INTO product(brandId,title) VALUES (100,'Sauce - Apple, Unsweetened');
INSERT INTO product(brandId,title) VALUES (1,'Sauce - Cranberry');
INSERT INTO product(brandId,title) VALUES (38,'Gingerale - Schweppes, 355 Ml');
INSERT INTO product(brandId,title) VALUES (67,'Ice Cream - Vanilla');
INSERT INTO product(brandId,title) VALUES (32,'Chocolate Eclairs');
INSERT INTO product(brandId,title) VALUES (24,'Lettuce - Boston Bib - Organic');
INSERT INTO product(brandId,title) VALUES (10,'Chicken Breast Wing On');
INSERT INTO product(brandId,title) VALUES (39,'Beer - Corona');
INSERT INTO product(brandId,title) VALUES (69,'Cheese - St. Paulin');
INSERT INTO product(brandId,title) VALUES (43,'Limes');
INSERT INTO product(brandId,title) VALUES (65,'Lemon Pepper');
INSERT INTO product(brandId,title) VALUES (46,'Beer - Upper Canada Lager');
INSERT INTO product(brandId,title) VALUES (19,'Coffee - Irish Cream');
INSERT INTO product(brandId,title) VALUES (42,'Juice - Prune');
INSERT INTO product(brandId,title) VALUES (70,'Figs');
INSERT INTO product(brandId,title) VALUES (43,'Potatoes - Mini Red');
INSERT INTO product(brandId,title) VALUES (22,'Oil - Pumpkinseed');
INSERT INTO product(brandId,title) VALUES (42,'Pasta - Angel Hair');
INSERT INTO product(brandId,title) VALUES (93,'Lime Cordial - Roses');
INSERT INTO product(brandId,title) VALUES (14,'Tomatoes - Diced, Canned');
INSERT INTO product(brandId,title) VALUES (3,'Anchovy Paste - 56 G Tube');
INSERT INTO product(brandId,title) VALUES (18,'Cheese - Parmigiano Reggiano');
INSERT INTO product(brandId,title) VALUES (96,'Flower - Carnations');
INSERT INTO product(brandId,title) VALUES (73,'Anchovy Fillets');
INSERT INTO product(brandId,title) VALUES (12,'Wonton Wrappers');
INSERT INTO product(brandId,title) VALUES (46,'Chicken - Wieners');
INSERT INTO product(brandId,title) VALUES (77,'Asparagus - Frozen');
INSERT INTO product(brandId,title) VALUES (43,'Tea Leaves - Oolong');
INSERT INTO product(brandId,title) VALUES (33,'Tart Shells - Barquettes, Savory');
INSERT INTO product(brandId,title) VALUES (36,'Beef Wellington');
INSERT INTO product(brandId,title) VALUES (97,'Macaroons - Two Bite Choc');
INSERT INTO product(brandId,title) VALUES (98,'Skirt - 29 Foot');
INSERT INTO product(brandId,title) VALUES (57,'Pork - Loin, Bone - In');
INSERT INTO product(brandId,title) VALUES (10,'Wine - Acient Coast Caberne');
INSERT INTO product(brandId,title) VALUES (88,'Lid - High Heat, Super Clear');
INSERT INTO product(brandId,title) VALUES (5,'Tea - Lemon Green Tea');
INSERT INTO product(brandId,title) VALUES (27,'The Pop Shoppe Pinapple');
INSERT INTO product(brandId,title) VALUES (85,'Flour - Cake');
INSERT INTO product(brandId,title) VALUES (64,'Muffin Batt - Blueberry Passion');
INSERT INTO product(brandId,title) VALUES (68,'Silicone Paper 16.5x24');
INSERT INTO product(brandId,title) VALUES (66,'Cheese - Taleggio D.o.p.');
INSERT INTO product(brandId,title) VALUES (51,'Tomato Paste');
INSERT INTO product(brandId,title) VALUES (34,'Salmon Steak - Cohoe 6 Oz');
INSERT INTO product(brandId,title) VALUES (45,'Artichokes - Knobless, White');
INSERT INTO product(brandId,title) VALUES (78,'Bonito Flakes - Toku Katsuo');
INSERT INTO product(brandId,title) VALUES (5,'Pheasants - Whole');
INSERT INTO product(brandId,title) VALUES (66,'Wine - Pinot Noir Latour');
INSERT INTO product(brandId,title) VALUES (6,'Wiberg Cure');
INSERT INTO product(brandId,title) VALUES (36,'Pasta - Lasagna Noodle, Frozen');
INSERT INTO product(brandId,title) VALUES (96,'Longos - Chicken Wings');
INSERT INTO product(brandId,title) VALUES (78,'Fruit Salad Deluxe');
INSERT INTO product(brandId,title) VALUES (81,'Pasta - Gnocchi, Potato');
INSERT INTO product(brandId,title) VALUES (41,'Pepper - Red Chili');
INSERT INTO product(brandId,title) VALUES (88,'Wine - Ej Gallo Sierra Valley');
INSERT INTO product(brandId,title) VALUES (65,'Savory');
INSERT INTO product(brandId,title) VALUES (56,'Beer - Original Organic Lager');
INSERT INTO product(brandId,title) VALUES (55,'Campari');
INSERT INTO product(brandId,title) VALUES (70,'Sprouts - Alfalfa');
INSERT INTO product(brandId,title) VALUES (25,'Oyster - In Shell');
INSERT INTO product(brandId,title) VALUES (75,'Sausage - Liver');
INSERT INTO product(brandId,title) VALUES (14,'Broom - Push');
INSERT INTO product(brandId,title) VALUES (18,'Port - 74 Brights');
INSERT INTO product(brandId,title) VALUES (22,'Wine - Touraine Azay - Le - Rideau');
INSERT INTO product(brandId,title) VALUES (23,'Wine - Vineland Estate Semi - Dry');
INSERT INTO product(brandId,title) VALUES (7,'Yogurt - Strawberry, 175 Gr');
INSERT INTO product(brandId,title) VALUES (37,'Wine - Cousino Macul Antiguas');
INSERT INTO product(brandId,title) VALUES (12,'Juice - Pineapple, 48 Oz');
INSERT INTO product(brandId,title) VALUES (34,'Wine - German Riesling');
INSERT INTO product(brandId,title) VALUES (56,'Mudslide');
INSERT INTO product(brandId,title) VALUES (84,'Beef - Eye Of Round');
INSERT INTO product(brandId,title) VALUES (36,'Ice Cream - Vanilla');
INSERT INTO product(brandId,title) VALUES (97,'Doilies - 8, Paper');
INSERT INTO product(brandId,title) VALUES (90,'Foam Tray S2');
INSERT INTO product(brandId,title) VALUES (56,'Chicken - Thigh, Bone In');
INSERT INTO product(brandId,title) VALUES (69,'Tomatoes - Grape');
INSERT INTO product(brandId,title) VALUES (31,'Chambord Royal');
INSERT INTO product(brandId,title) VALUES (59,'Beer - True North Lager');
INSERT INTO product(brandId,title) VALUES (54,'Soup Campbells Beef With Veg');
INSERT INTO product(brandId,title) VALUES (65,'Corn Shoots');
INSERT INTO product(brandId,title) VALUES (91,'Vinegar - Red Wine');
INSERT INTO product(brandId,title) VALUES (71,'Capers - Pickled');
INSERT INTO product(brandId,title) VALUES (73,'Beef Cheek Fresh');
INSERT INTO product(brandId,title) VALUES (70,'Coconut Milk - Unsweetened');
INSERT INTO product(brandId,title) VALUES (62,'Sesame Seed');
INSERT INTO product(brandId,title) VALUES (62,'Soup - Knorr, Country Bean');
INSERT INTO product(brandId,title) VALUES (82,'Veal - Insides, Grains');
INSERT INTO product(brandId,title) VALUES (57,'Pork Casing');
INSERT INTO product(brandId,title) VALUES (89,'Orange Roughy 4/6 Oz');
INSERT INTO product(brandId,title) VALUES (28,'Tea - Mint');
INSERT INTO product(brandId,title) VALUES (70,'Coffee Caramel Biscotti');
INSERT INTO product(brandId,title) VALUES (20,'Alize Gold Passion');
INSERT INTO product(brandId,title) VALUES (63,'Cloves - Ground');
INSERT INTO product(brandId,title) VALUES (62,'Wine - Shiraz South Eastern');
INSERT INTO product(brandId,title) VALUES (37,'Carrots - Mini, Stem On');
INSERT INTO product(brandId,title) VALUES (55,'Oil - Avocado');
INSERT INTO product(brandId,title) VALUES (21,'Yeast Dry - Fermipan');
INSERT INTO product(brandId,title) VALUES (4,'Sea Urchin');
INSERT INTO product(brandId,title) VALUES (74,'Pears - Anjou');
INSERT INTO product(brandId,title) VALUES (97,'Longos - Chicken Curried');
INSERT INTO product(brandId,title) VALUES (71,'Myers Planters Punch');
INSERT INTO product(brandId,title) VALUES (4,'Chocolate Bar - Oh Henry');
INSERT INTO product(brandId,title) VALUES (13,'Broom And Brush Rack Black');
INSERT INTO product(brandId,title) VALUES (98,'Wine - Vineland Estate Semi - Dry');
INSERT INTO product(brandId,title) VALUES (10,'Cup - 6oz, Foam');
INSERT INTO product(brandId,title) VALUES (37,'Wine - Port Late Bottled Vintage');
INSERT INTO product(brandId,title) VALUES (87,'Toamtoes 6x7 Select');
INSERT INTO product(brandId,title) VALUES (21,'Temperature Recording Station');
INSERT INTO product(brandId,title) VALUES (3,'Pepper - Black, Ground');
INSERT INTO product(brandId,title) VALUES (8,'Coffee Swiss Choc Almond');
INSERT INTO product(brandId,title) VALUES (13,'Pasta - Penne Primavera, Single');
INSERT INTO product(brandId,title) VALUES (64,'Ham - Procutinni');
INSERT INTO product(brandId,title) VALUES (90,'Mushroom - Trumpet, Dry');
INSERT INTO product(brandId,title) VALUES (26,'Bag - Clear 7 Lb');
INSERT INTO product(brandId,title) VALUES (34,'Mangostein');
INSERT INTO product(brandId,title) VALUES (47,'Oven Mitts - 15 Inch');
INSERT INTO product(brandId,title) VALUES (19,'Bread - Pain Au Liat X12');
INSERT INTO product(brandId,title) VALUES (37,'Corn - Mini');
INSERT INTO product(brandId,title) VALUES (84,'Ice Cream - Chocolate');
INSERT INTO product(brandId,title) VALUES (47,'Chocolate Bar - Oh Henry');
INSERT INTO product(brandId,title) VALUES (81,'Squash - Guords');
INSERT INTO product(brandId,title) VALUES (4,'Coconut - Shredded, Sweet');
INSERT INTO product(brandId,title) VALUES (35,'Lemons');
INSERT INTO product(brandId,title) VALUES (49,'Nut - Almond, Blanched, Sliced');
INSERT INTO product(brandId,title) VALUES (18,'Urban Zen Drinks');
INSERT INTO product(brandId,title) VALUES (99,'Juice - Apple 284ml');
INSERT INTO product(brandId,title) VALUES (81,'Veal - Brisket, Provimi, Bone - In');
INSERT INTO product(brandId,title) VALUES (23,'Appetiser - Bought');
INSERT INTO product(brandId,title) VALUES (71,'Baking Powder');
INSERT INTO product(brandId,title) VALUES (99,'Carbonated Water - Peach');
INSERT INTO product(brandId,title) VALUES (84,'Pastry - Cherry Danish - Mini');
INSERT INTO product(brandId,title) VALUES (68,'Fib N9 - Prague Powder');
INSERT INTO product(brandId,title) VALUES (55,'Beef - Rouladin, Sliced');
INSERT INTO product(brandId,title) VALUES (53,'Chocolate Bar - Reese Pieces');
INSERT INTO product(brandId,title) VALUES (19,'Vinegar - Rice');
INSERT INTO product(brandId,title) VALUES (59,'Mint - Fresh');
INSERT INTO product(brandId,title) VALUES (58,'Duck - Legs');
INSERT INTO product(brandId,title) VALUES (72,'Shrimp - Black Tiger 16/20');
INSERT INTO product(brandId,title) VALUES (52,'Table Cloth 54x54 White');
INSERT INTO product(brandId,title) VALUES (1,'Cumin - Ground');
INSERT INTO product(brandId,title) VALUES (59,'Fireball Whisky');
INSERT INTO product(brandId,title) VALUES (79,'Iced Tea Concentrate');
INSERT INTO product(brandId,title) VALUES (85,'Coconut - Shredded, Sweet');
INSERT INTO product(brandId,title) VALUES (50,'Plastic Wrap');
INSERT INTO product(brandId,title) VALUES (54,'Kellogs All Bran Bars');
INSERT INTO product(brandId,title) VALUES (69,'Pork - Hock And Feet Attached');
INSERT INTO product(brandId,title) VALUES (47,'Wine - Peller Estates Late');
INSERT INTO product(brandId,title) VALUES (72,'Tomato - Peeled Italian Canned');
INSERT INTO product(brandId,title) VALUES (84,'Mahi Mahi');
INSERT INTO product(brandId,title) VALUES (47,'Sauce - White, Mix');
INSERT INTO product(brandId,title) VALUES (36,'Octopus - Baby, Cleaned');
INSERT INTO product(brandId,title) VALUES (23,'Oil - Macadamia');
INSERT INTO product(brandId,title) VALUES (78,'Creme De Cacao White');
INSERT INTO product(brandId,title) VALUES (49,'Pomegranates');
INSERT INTO product(brandId,title) VALUES (79,'Liners - Baking Cups');
INSERT INTO product(brandId,title) VALUES (5,'Mushroom - Chanterelle, Dry');
INSERT INTO product(brandId,title) VALUES (81,'Duck - Whole');
INSERT INTO product(brandId,title) VALUES (12,'Olives - Stuffed');
INSERT INTO product(brandId,title) VALUES (66,'Bread - White, Sliced');
INSERT INTO product(brandId,title) VALUES (52,'Yogurt - Assorted Pack');
INSERT INTO product(brandId,title) VALUES (46,'Pepper - Gypsy Pepper');
INSERT INTO product(brandId,title) VALUES (72,'White Baguette');
INSERT INTO product(brandId,title) VALUES (74,'Garlic - Peeled');
INSERT INTO product(brandId,title) VALUES (4,'Rootbeer');
INSERT INTO product(brandId,title) VALUES (67,'Apple - Macintosh');
INSERT INTO product(brandId,title) VALUES (41,'Salmon - Atlantic, No Skin');
INSERT INTO product(brandId,title) VALUES (99,'Squash - Pepper');
INSERT INTO product(brandId,title) VALUES (45,'Pepper - Cayenne');
INSERT INTO product(brandId,title) VALUES (61,'Carrots - Jumbo');
INSERT INTO product(brandId,title) VALUES (71,'Vacuum Bags 12x16');
INSERT INTO product(brandId,title) VALUES (74,'Wine - Red, Cooking');
INSERT INTO product(brandId,title) VALUES (2,'Ecolab Silver Fusion');
INSERT INTO product(brandId,title) VALUES (51,'Flower - Commercial Spider');
INSERT INTO product(brandId,title) VALUES (85,'Bread - Calabrese Baguette');
INSERT INTO product(brandId,title) VALUES (49,'Cookies - Englishbay Oatmeal');
INSERT INTO product(brandId,title) VALUES (79,'Foam Tray S2');
INSERT INTO product(brandId,title) VALUES (78,'Lettuce - California Mix');
INSERT INTO product(brandId,title) VALUES (88,'Hummus - Spread');
INSERT INTO product(brandId,title) VALUES (38,'Dasheen');
INSERT INTO product(brandId,title) VALUES (80,'Onions Granulated');
INSERT INTO product(brandId,title) VALUES (4,'Pepper - Cubanelle');
INSERT INTO product(brandId,title) VALUES (72,'Turkey - Breast, Double');
INSERT INTO product(brandId,title) VALUES (100,'Shrimp - Black Tiger 16/20');
INSERT INTO product(brandId,title) VALUES (44,'Wine - White, Colubia Cresh');
INSERT INTO product(brandId,title) VALUES (54,'Lettuce - Romaine, Heart');
INSERT INTO product(brandId,title) VALUES (24,'Garbage Bags - Clear');
INSERT INTO product(brandId,title) VALUES (23,'Plate Pie Foil');
INSERT INTO product(brandId,title) VALUES (98,'Island Oasis - Magarita Mix');
INSERT INTO product(brandId,title) VALUES (78,'Appetizer - Chicken Satay');
INSERT INTO product(brandId,title) VALUES (24,'Foam Cup 6 Oz');
INSERT INTO product(brandId,title) VALUES (47,'Soup - Campbells, Chix Gumbo');
INSERT INTO product(brandId,title) VALUES (69,'Lid - 0090 Clear');
INSERT INTO product(brandId,title) VALUES (8,'Beans - Black Bean, Preserved');
INSERT INTO product(brandId,title) VALUES (83,'Wine - White, Riesling, Semi - Dry');
INSERT INTO product(brandId,title) VALUES (53,'Butter - Pod');
INSERT INTO product(brandId,title) VALUES (34,'Wine - Spumante Bambino White');
INSERT INTO product(brandId,title) VALUES (66,'Rice - Long Grain');
INSERT INTO product(brandId,title) VALUES (87,'Longos - Chicken Curried');
INSERT INTO product(brandId,title) VALUES (7,'Browning Caramel Glace');
INSERT INTO product(brandId,title) VALUES (16,'Tobasco Sauce');
INSERT INTO product(brandId,title) VALUES (97,'Wine - Port Late Bottled Vintage');
INSERT INTO product(brandId,title) VALUES (85,'Cheese - Gorgonzola');
INSERT INTO product(brandId,title) VALUES (39,'Snapple Raspberry Tea');
INSERT INTO product(brandId,title) VALUES (28,'Chicken - Whole');
INSERT INTO product(brandId,title) VALUES (13,'Sauce - Marinara');
INSERT INTO product(brandId,title) VALUES (8,'Blueberries');
INSERT INTO product(brandId,title) VALUES (93,'Sunflower Seed Raw');
INSERT INTO product(brandId,title) VALUES (20,'Soup - Cream Of Broccoli');
INSERT INTO product(brandId,title) VALUES (12,'Tart - Raisin And Pecan');
INSERT INTO product(brandId,title) VALUES (41,'Tortillas - Flour, 10');
INSERT INTO product(brandId,title) VALUES (9,'Wine - Manischewitz Concord');
INSERT INTO product(brandId,title) VALUES (11,'Wine - Pinot Noir Latour');
INSERT INTO product(brandId,title) VALUES (8,'Bread - Malt');
INSERT INTO product(brandId,title) VALUES (77,'Soup - Campbells, Cream Of');
INSERT INTO product(brandId,title) VALUES (76,'Pickles - Gherkins');
INSERT INTO product(brandId,title) VALUES (61,'Beef - Short Ribs');
INSERT INTO product(brandId,title) VALUES (8,'Clam Nectar');
INSERT INTO product(brandId,title) VALUES (25,'Calvados - Boulard');
INSERT INTO product(brandId,title) VALUES (23,'Glass - Juice Clear 5oz 55005');
INSERT INTO product(brandId,title) VALUES (46,'Venison - Denver Leg Boneless');
INSERT INTO product(brandId,title) VALUES (54,'Pasta - Lasagna, Dry');
INSERT INTO product(brandId,title) VALUES (33,'Beer - Tetleys');
INSERT INTO product(brandId,title) VALUES (58,'Savory');
INSERT INTO product(brandId,title) VALUES (7,'Milkettes - 2%');
INSERT INTO product(brandId,title) VALUES (93,'Wine - Prosecco Valdobiaddene');
INSERT INTO product(brandId,title) VALUES (51,'Guinea Fowl');
INSERT INTO product(brandId,title) VALUES (33,'Oven Mitt - 13 Inch');
INSERT INTO product(brandId,title) VALUES (40,'Wine - Red, Metus Rose');
INSERT INTO product(brandId,title) VALUES (12,'Bandage - Fexible 1x3');
INSERT INTO product(brandId,title) VALUES (25,'Cinnamon Rolls');
INSERT INTO product(brandId,title) VALUES (46,'Bread - Bagels, Plain');
INSERT INTO product(brandId,title) VALUES (72,'Pineapple - Golden');
INSERT INTO product(brandId,title) VALUES (84,'Beef - Outside, Round');
INSERT INTO product(brandId,title) VALUES (36,'Wine - Duboeuf Beaujolais');
INSERT INTO product(brandId,title) VALUES (49,'Bagelers');
INSERT INTO product(brandId,title) VALUES (47,'Fond - Neutral');
INSERT INTO product(brandId,title) VALUES (13,'Soupcontfoam16oz 116con');
INSERT INTO product(brandId,title) VALUES (27,'Shrimp - 16/20, Peeled Deviened');
INSERT INTO product(brandId,title) VALUES (41,'Bag Stand');
INSERT INTO product(brandId,title) VALUES (9,'Bread - Olive');
INSERT INTO product(brandId,title) VALUES (29,'Truffle Paste');
INSERT INTO product(brandId,title) VALUES (3,'Squid - U 5');
INSERT INTO product(brandId,title) VALUES (63,'Wine - Tio Pepe Sherry Fino');
INSERT INTO product(brandId,title) VALUES (60,'Maintenance Removal Charge');
INSERT INTO product(brandId,title) VALUES (91,'Bacardi Mojito');
INSERT INTO product(brandId,title) VALUES (72,'Ham - Cooked');
INSERT INTO product(brandId,title) VALUES (20,'Chick Peas - Canned');
INSERT INTO product(brandId,title) VALUES (13,'Wine - Magnotta - Red, Baco');
INSERT INTO product(brandId,title) VALUES (78,'Wine - Periguita Fonseca');
INSERT INTO product(brandId,title) VALUES (42,'Pasta - Detalini, White, Fresh');
INSERT INTO product(brandId,title) VALUES (65,'Onion - Dried');
INSERT INTO product(brandId,title) VALUES (61,'Sauce - Oyster');
INSERT INTO product(brandId,title) VALUES (36,'Beef - Ox Tail, Frozen');
INSERT INTO product(brandId,title) VALUES (12,'Kellogs All Bran Bars');
INSERT INTO product(brandId,title) VALUES (77,'Bread - Sticks, Thin, Plain');
INSERT INTO product(brandId,title) VALUES (35,'Chicken - Whole Fryers');
INSERT INTO product(brandId,title) VALUES (22,'Pasta - Lasagne, Fresh');
INSERT INTO product(brandId,title) VALUES (43,'Versatainer Nc - 8288');
INSERT INTO product(brandId,title) VALUES (85,'Initation Crab Meat');
INSERT INTO product(brandId,title) VALUES (32,'Cranberries - Dry');
INSERT INTO product(brandId,title) VALUES (41,'Bulgar');
INSERT INTO product(brandId,title) VALUES (53,'Chinese Foods - Chicken');
INSERT INTO product(brandId,title) VALUES (43,'Salmon Steak - Cohoe 8 Oz');
INSERT INTO product(brandId,title) VALUES (39,'Coffee - Frthy Coffee Crisp');
INSERT INTO product(brandId,title) VALUES (24,'Spice - Greek 1 Step');
INSERT INTO product(brandId,title) VALUES (66,'Onions - Red Pearl');
INSERT INTO product(brandId,title) VALUES (57,'Beef - Tongue, Fresh');
INSERT INTO product(brandId,title) VALUES (74,'Lotus Rootlets - Canned');
INSERT INTO product(brandId,title) VALUES (90,'Lobak');
INSERT INTO product(brandId,title) VALUES (71,'Savory');
INSERT INTO product(brandId,title) VALUES (9,'Pork - Back Ribs');
INSERT INTO product(brandId,title) VALUES (4,'Trueblue - Blueberry 12x473ml');
INSERT INTO product(brandId,title) VALUES (79,'Wine - Two Oceans Sauvignon');
INSERT INTO product(brandId,title) VALUES (8,'Wine - Pinot Noir Stoneleigh');
INSERT INTO product(brandId,title) VALUES (84,'Mustard - Seed');
INSERT INTO product(brandId,title) VALUES (52,'Lobster - Base');
INSERT INTO product(brandId,title) VALUES (92,'Oil - Shortening - All - Purpose');
INSERT INTO product(brandId,title) VALUES (9,'Spice - Onion Powder Granulated');
INSERT INTO product(brandId,title) VALUES (71,'Bread - Pumpernickel');
INSERT INTO product(brandId,title) VALUES (31,'Wine - Jaboulet Cotes Du Rhone');
INSERT INTO product(brandId,title) VALUES (96,'Pepper Squash');
INSERT INTO product(brandId,title) VALUES (22,'Pie Filling - Apple');
INSERT INTO product(brandId,title) VALUES (47,'Magnotta - Bel Paese White');
INSERT INTO product(brandId,title) VALUES (25,'Tarragon - Fresh');
INSERT INTO product(brandId,title) VALUES (47,'Muffin Puck Ww Carrot');
INSERT INTO product(brandId,title) VALUES (79,'Parsley - Fresh');
INSERT INTO product(brandId,title) VALUES (17,'Piping - Bags Quizna');
INSERT INTO product(brandId,title) VALUES (51,'Rootbeer');
INSERT INTO product(brandId,title) VALUES (35,'Oil - Canola');
INSERT INTO product(brandId,title) VALUES (77,'Wine - Sawmill Creek Autumn');
INSERT INTO product(brandId,title) VALUES (87,'Sloe Gin - Mcguinness');
INSERT INTO product(brandId,title) VALUES (76,'Wine - Soave Folonari');
INSERT INTO product(brandId,title) VALUES (35,'Toothpick Frilled');
INSERT INTO product(brandId,title) VALUES (41,'Sorrel - Fresh');
INSERT INTO product(brandId,title) VALUES (70,'Cups 10oz Trans');
INSERT INTO product(brandId,title) VALUES (18,'Beef Dry Aged Tenderloin Aaa');
INSERT INTO product(brandId,title) VALUES (11,'Ocean Spray - Kiwi Strawberry');
INSERT INTO product(brandId,title) VALUES (32,'Wine - Sake');
INSERT INTO product(brandId,title) VALUES (35,'Wine - White, Mosel Gold');
INSERT INTO product(brandId,title) VALUES (94,'Soup - French Can Pea');
INSERT INTO product(brandId,title) VALUES (62,'Plaintain');
INSERT INTO product(brandId,title) VALUES (5,'Kale - Red');
INSERT INTO product(brandId,title) VALUES (15,'Red Pepper Paste');
INSERT INTO product(brandId,title) VALUES (25,'Soup - French Onion');
INSERT INTO product(brandId,title) VALUES (52,'Mushroom - White Button');
INSERT INTO product(brandId,title) VALUES (14,'Lettuce Romaine Chopped');
INSERT INTO product(brandId,title) VALUES (89,'Chef Hat 20cm');
INSERT INTO product(brandId,title) VALUES (32,'Chicken - Thigh, Bone In');